tests - fixture
documentsJsonString

	^ '[
    {
        "id": 1,
        "title": "Exploring AI: The Future of Technology",
        "contents": "Artificial Intelligence (AI) is transforming the digital landscape. From autonomous driving to automated customer service, AI technology is everywhere and it is the future of technology."
    },
    {
        "id": 2,
        "title": "AI and Space: The Future is Here",
        "contents": "The fusion of AI and space exploration has taken significant leaps in recent years. The discovery of water on Mars and the ambition of landing humans on Mars, all with the help of AI, has piqued interest."
    },
    {
        "id": 3,
        "title": "A Guide to Healthy Eating",
        "contents": "Eating a balanced diet is vital for health and wellbeing. Food provides our bodies with the energy, protein, essential fats, vitamins and minerals to live, grow and function properly."
    },
    {
        "id": 4,
        "title": "The Internet and AI",
        "contents": "The internet has revolutionized the computer and communications world like nothing before. The invention of the telegraph, telephone, radio, and computer set the stage for this unprecedented integration of capabilities. Now, with the advancement of AI, we can expect even more changes."
    },
    {
        "id": 5,
        "title": "The Art of Photography",
        "contents": "Photography is the science, art, application and practice of creating durable images by recording light or other electromagnetic radiation, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film."
    }
]
'