tests - fixture
documentsJsonString

	^ '
[
     {
         "id": 1,
         "title": "Why AI is the Future",
         "contents": "Artificial Intelligence is transforming the digital landscape. From autonomous driving to automated customer service, AI technology is everywhere."
     },
     {
         "id": 2,
         "title": "Exploring the Outer Space",
         "contents": "Space exploration has taken some significant leaps in recent years. The discovery of water on Mars and the ambition of landing humans on Mars has piqued interest."
     },
     {
         "id": 3,
         "title": "A Guide to Healthy Eating",
         "contents": "Eating a balanced diet is vital for health and wellbeing. Food provides our bodies with the energy, protein, essential fats, vitamins and minerals to live, grow and function properly."
     },
     {
         "id": 4,
         "title": "History of the Internet",
         "contents": "The internet has revolutionized the computer and communications world like nothing before. The invention of the telegraph, telephone, radio, and computer set the stage for this unprecedented integration of capabilities."
     },
     {
         "id": 5,
         "title": "The Art of Photography",
         "contents": "Photography is the science, art, application and practice of creating durable images by recording light or other electromagnetic radiation, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film."
     }
]'