tests - fixture
facetsDocumentsJsonString

	^ '[
  {
    "id": 5,
    "title": "Hard Times",
    "genres": [
      "Classics",
      "Fiction",
      "Victorian",
      "Literature"
    ],
    "language": "English",
    "author": "Charles Dickens"
  },
  {
    "id": 6,
    "title": "Pride and Prejudice",
    "genres": [
      "Classics",
      "Romance",
      "Literature"
    ],
    "language": "English",
    "author": "Jane Austen"
  },
  {
    "id": 7,
    "title": "Moby Dick",
    "genres": [
      "Classics",
      "Adventure",
      "Literature"
    ],
    "language": "English",
    "author": "Herman Melville"
  },
  {
    "id": 8,
    "title": "The Great Gatsby",
    "genres": [
      "Classics",
      "Fiction",
      "Literature",
      "American"
    ],
    "language": "English",
    "author": "F. Scott Fitzgerald"
  },
  {
    "id": 9,
    "title": "War and Peace",
    "genres": [
      "Classics",
      "Historical",
      "Literature",
      "Russian"
    ],
    "language": "English",
    "author": "Leo Tolstoy"
  },
  {
    "id": 10,
    "title": "To Kill a Mockingbird",
    "genres": [
      "Classics",
      "Historical",
      "Literature",
      "American"
    ],
    "language": "English",
    "author": "Harper Lee"
  },
  {
    "id": 11,
    "title": "Alice''''s Adventures in Wonderland",
    "genres": [
      "Children''''s Literature",
      "Classics",
      "Fantasy"
    ],
    "language": "English",
    "author": "Lewis Carroll"
  },
  {
    "id": 12,
    "title": "Charlotte''''s Web",
    "genres": [
      "Children''''s Literature",
      "Classics"
    ],
    "language": "English",
    "author": "E.B. White"
  },
  {
    "id": 13,
    "title": "The Hitchhiker''''s Guide to the Galaxy",
    "genres": [
      "Comedy",
      "Science Fiction",
      "Adventure"
    ],
    "language": "English",
    "author": "Douglas Adams"
  },
  {
    "id": 14,
    "title": "Much Ado About Nothing",
    "genres": [
      "Comedy",
      "Classics",
      "Drama"
    ],
    "language": "English",
    "author": "William Shakespeare"
  },
  {
    "id": 15,
    "title": "Matilda",
    "genres": [
      "Children''''s Literature",
      "Comedy",
      "Classics"
    ],
    "language": "English",
    "author": "Roald Dahl"
  }
]'