tests - fixture
vectorDocumentsJsonString

	^ '[
    {
        "title": "AAA",
        "id": 1,
        "_vectors": [
            0,
            0.8,
            -0.2
        ]
    },
    {
        "title": "BBB",
        "id": 2,
        "_vectors": [
            1,
            -0.2,
            0
        ]
    },
    {
        "title": "CCC",
        "id": 3,
        "_vectors": [
            1,
            2,
            3
        ]
    }
]'