tests - fixture
vectorDocumentsJsonString

	^ '[
    {
        "title": "AAA",
        "id": 1,
        "_vectors": {
            "mock": [
                0.2,
                0.3,
                0.4
            ]
        }
    },
    {
        "title": "Zero Vector Item",
        "id": 2,
        "_vectors": {
            "mock": [
                0,
                0,
                0
            ]
        }
    },
    {
        "title": "BBB",
        "id": 3,
        "_vectors": {
            "mock": [
                -0.81,
                0.8,
                0.61
            ]
        }
    },
    {
        "title": "CCC",
        "id": 4,
        "_vectors": {
            "mock": [
                0.51,
                0.91,
                -0.34
            ]
        }
    },
    {
        "title": "DDD",
        "id": 5,
        "_vectors": {
            "mock": [
                -0.97,
                0.92,
                -0.22
            ]
        }
    },
    {
        "title": "EEE",
        "id": 6,
        "_vectors": {
            "mock": [
                0.0,
                0.27,
                -0.88
            ]
        }
    },
    {
        "title": "FFF",
        "id": 7,
        "_vectors": {
            "mock": [
                -0.26,
                0.56,
                0.11
            ]
        }
    },
    {
        "title": "GGG",
        "id": 8,
        "_vectors": {
            "mock": [
                -0.46,
                0.84,
                -0.7
            ]
        }
    },
    {
        "title": "HHH",
        "id": 9,
        "_vectors": {
            "mock": [
                0.96,
                -0.46,
                -0.42
            ]
        }
    },
    {
        "title": "III",
        "id": 10,
        "_vectors": {
            "mock": [
                0.58,
                -0.32,
                -0.18
            ]
        }
    },
    {
        "title": "JJJ",
        "id": 11,
        "_vectors": {
            "mock": [
                0.68,
                -0.19,
                0.72
            ]
        }
    },
    {
        "title": "KKK",
        "id": 12,
        "_vectors": {
            "mock": [
                0.04,
                0.4,
                0.96
            ]
        }
    },
    {
        "title": "LLL",
        "id": 13,
        "_vectors": {
            "mock": [
                -0.06,
                -0.71,
                0.81
            ]
        }
    },
    {
        "title": "MMM",
        "id": 14,
        "_vectors": {
            "mock": [
                0.4,
                0.6,
                0.8
            ]
        }
    },
    {
        "title": "NNN",
        "id": 15,
        "_vectors": {
            "mock": [
                0.17,
                0.37,
                0.08
            ]
        }
    },
    {
        "title": "OOO",
        "id": 16,
        "_vectors": {
            "mock": [
                -0.34,
                -0.67,
                0.89
            ]
        }
    },
    {
        "title": "PPP",
        "id": 17,
        "_vectors": {
            "mock": [
                -0.4,
                -0.35,
                0.1
            ]
        }
    },
    {
        "title": "QQQ",
        "id": 18,
        "_vectors": {
            "mock": [
                -0.2,
                -0.3,
                -0.4
            ]
        }
    },
    {
        "title": "RRR",
        "id": 19,
        "_vectors": {
            "mock": [
                0.48,
                0.28,
                0.64
            ]
        }
    },
    {
        "title": "SSS",
        "id": 20,
        "_vectors": {
            "mock": [
                0.48,
                0.28,
                0.64
            ]
        }
    }
]'